# Generated by Django 5.2.1 on 2025-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
