# Generated by Django 5.2.1 on 2025-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='image_url',
            field=models.URLField(help_text='Supabase Storage에 업로드된 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.URLField(blank=True, help_text='Supabase 이미지 URL 또는 외부 링크', null=True),
        ),
    ]
