# Generated by Django 5.2.1 on 2025-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_section_image_url_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='car_image_url',
            field=models.URLField(blank=True, help_text='차량 이미지 URL', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='car_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.URLField(blank=True, help_text='리뷰어 사진 URL', null=True),
        ),
    ]
