# Generated by Django 5.2.1 on 2025-05-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_benefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='is_sent_kakao',
            new_name='is_sent_email',
        ),
    ]
