# Generated by Django 5.2.1 on 2025-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_is_sent_kakao_inquiry_is_sent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sec6_1', 'sec6_1'), ('sec6_2', 'sec6_2'), ('sec6_3', 'sec6_3'), ('review1', 'review1'), ('review2', 'review2'), ('review3', 'review3'), ('reviewcar1', 'reviewcar1'), ('reviewcar2', 'reviewcar2'), ('reviewcar3', 'reviewcar3')], help_text='교체할 이미지 이름 (확장자 제외)', max_length=50, unique=True)),
                ('file', models.FileField(upload_to='temp/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
