# Generated by Django 5.2.1 on 2025-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imageslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
