# Generated by Django 5.2.1 on 2025-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_benefit_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='price',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='car_image_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='car_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
