# Generated by Django 5.2.1 on 2025-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_testimonial_car_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
